# -*- coding: utf-8 -*-
"""Yolo_V11_Training_And_Validation_File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EPjFHLlPcYwa5oeSuwm-Mjg4SVE_VTjw
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
ultralytics.checks()

from google.colab import drive
drive.mount('/content/drive')

# Download COCO val
import torch
torch.hub.download_url_to_file('https://ultralytics.com/assets/coco2017val.zip', 'tmp.zip')  # download (780M - 5000 images)
!unzip -q tmp.zip -d datasets && rm tmp.zip  # unzip

# Validate YOLO11n on COCO8 val
!yolo val model=yolo11n.pt data='/content/drive/MyDrive/MIT/augmented.yaml'

# Train YOLO11n on COCO8 for 3 epochs
!yolo train model=yolo11n.pt data='/content/drive/MyDrive/MIT/augmented.yaml' epochs=500 imgsz=640

# Run inference on an image with YOLO11n
!yolo predict model='/content/runs/detect/train5/weights/best.pt' source= '/content/drive/MyDrive/yolo/test/images/7117_Caranx_sexfasciatus_juvenile_f000003_RGHS_jpg.rf.c41ade83491275abda255248ac837fe3.jpg'